// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKline(arg1, arg2) {
  return window['go']['main']['App']['GetKline'](arg1, arg2);
}

export function GetupDown() {
  return window['go']['main']['App']['GetupDown']();
}
