// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetKline(arg1:string,arg2:number):Promise<Array<main.Kline>>;

export function GetupDown():Promise<Array<main.IndexData>>;
